
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IP_ADRESSES](
	[ID_IP_ADRESS] [int] IDENTITY(1,1) NOT NULL,
	[IP_ADRESS] [nvarchar](20) NULL,
 CONSTRAINT [PK_IP_ADRESSES] PRIMARY KEY CLUSTERED 
(
	[ID_IP_ADRESS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
