

CREATE TABLE [dbo].[IP_ADRESSES_DATA](
	[ID_IP_ADRESSES_DATA] [int] IDENTITY(1,1) NOT NULL,
	[ID_IP_ADRESS] [int] NOT NULL,
	[ID_DATA_TYPE] [bigint] NOT NULL,
	[VALUE] [sql_variant] NULL,
 CONSTRAINT [ID_IP_ADRESSES_DATA] PRIMARY KEY CLUSTERED 
(
	[ID_IP_ADRESSES_DATA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


