
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DATA_TYPE_CLASS](
	[ID_DATA_TYPE_CLASS] [int] NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_DATA_TYPE_CLASS] PRIMARY KEY CLUSTERED 
(
	[ID_DATA_TYPE_CLASS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO