

/****** Object:  Table [dbo].[DATA_TYPE]    Script Date: 30.11.2019 23:10:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DATA_TYPE](
	[ID_DATA_TYPE] [bigint] NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[ID_DATA_TYPE_CLASS] [int] NOT NULL,
 CONSTRAINT [PK_DATA_TYPE] PRIMARY KEY CLUSTERED 
(
	[ID_DATA_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



ALTER TABLE [dbo].[DATA_TYPE]  WITH CHECK ADD  CONSTRAINT [FK_DATA_TYPE_DATA_TYPE_CLASS] FOREIGN KEY([ID_DATA_TYPE_CLASS])
REFERENCES [dbo].[DATA_TYPE_CLASS] ([ID_DATA_TYPE_CLASS])
GO

ALTER TABLE [dbo].[DATA_TYPE] CHECK CONSTRAINT [FK_DATA_TYPE_DATA_TYPE_CLASS]
GO


